### ISSUE TITLE
Text cut off on some modules

### ISSUE THREAD

**Issue by KoB-Kirito** [GDQuest/learn-gdscript#785]
**Describe the bug**
The text is cut off on these modules.
6. Your first function parameter > Drawing squares of any size
14. Multiplying > Reducing damage at higher levels

**Screenshots**
![grafik](https://user-images.githubusercontent.com/51691757/220613291-20b84884-efaf-43d5-9538-e93934cdf43b.png)
![grafik](https://user-images.githubusercontent.com/51691757/220623599-441fdedd-52a1-4f59-a27a-a439fcd15a95.png)

**Information about your device (please complete the following information):**
 - Operating System: Windows
 - Browser: Firefox

**Comment by NathanLovato** [comment]
@Razoric480 Could you please look into this?

This issue happens less now, but it still does happen when setting the text size in the settings to the higher setting levels in the practices. Direct link to L6.P3: https://gdquest.github.io/learn-gdscript/staging/#learn-gdscript/multiple-function-parameters/$drawing-squares-of-any-size

This is most certainly due to increasing the minimum width of the central element, either automatically or by literally changing the minimum size property. We should make sure that the total width of panels can never overflow the width of the viewport, margins included - one way or another, we should clamp the min size of the elements, we should make sure nothing also grows too much.

Check also the Run Pause etc. buttons below the code editor, they might also be causing trouble.

**Comment by Razoric480** [comment]
I can't recreate it, in browser or editor, even cranking the text size to maximum. Might have been fixed since this was issued.

<img width="2038" height="1283" alt="Image" src="https://github.com/user-attachments/assets/b8578a3b-d57d-4815-809a-025221211a75" />

**Comment by ronttizz** [comment]
Similar text cut off happened to me with middle sized text sizes in Lesson 25. Not sure if this happens in other similar code examples. Here is a screenshot.

EDIT:
The end of code examples is not visible even when scrolling all the way to right.
OS: Windows 11
Browser: Brave 1.89.137 (Chromium 147.0.7727.102)

<img width="1143" height="577" alt="Image" src="https://github.com/user-attachments/assets/ac045fe0-3d9d-4bf3-88af-b1aee2ddbef0" />

**Comment by NathanLovato** [comment]
@ronttizz could you please give it a try with this version of the application? This is a direct link to lesson 25: https://gdquest.github.io/learn-gdscript/staging/#learn-gdscript/looping-over-dictionaries

We're in the process of reworking it, hopefully text visibility with scrollbars should be more reliable now.

**Comment by NathanLovato** [comment]
@Razoric480 On my end it does still happen (latest staging HTML5 version): 

<img width="3462" height="1922" alt="Image" src="https://github.com/user-attachments/assets/d566c700-161f-48fc-8d84-c5682d97fd75" />

I would bet it's the central buttons, because if I change the application to Japanese, the text, or Chinese, the text is shorter there and everything fits at the same font size. I don't understand why it happens for me and not for you, that is unexpected.

Then I'm not sure what would be best for the buttons, if they should be in a flow container and take more rows, taking vertical space from the container, or if their icon and text should scale automatically to keep them within the bounds of the central column.

<img width="3462" height="1922" alt="Image" src="https://github.com/user-attachments/assets/28de41ef-dcf7-4c60-83bd-62ab962a064f" />
